fix(builds): handle release branch already existing

diff --git a/.github/workflows/test-custom-release.yaml b/.github/workflows/test-custom-release.yaml
--- a/.github/workflows/test-custom-release.yaml
+++ b/.github/workflows/test-custom-release.yaml
@@ -1,24 +1,16 @@
 name: Create or Update Release Branch
 
 on:
+  workflow_dispatch:
   push:
     branches:
       - dev
-  workflow_dispatch:
-
-jobs:
-  name: Create Release Tag on Release Merge
-
-  on:
-    push:
-      branches:
-        - dev
 
   jobs:
     create-tag:
       name: Create Release Tag
       runs-on: ubuntu-latest
-      if: github.ref.startsWith('refs/heads/release/')
+      if: ${{ contains(github.ref_name, 'release/') }}
       steps:
         - name: Checkout Repository
           uses: actions/checkout@v4
@@ -47,10 +39,15 @@ jobs:
             git tag -a "${{ env.new_tag }}" -m "Release ${{ env.new_tag }}"
             git push origin "${{ env.new_tag }}"
 
+  changed-images:
+    if: "github.event_name == 'push' && ${{ !contains(github.ref_name, 'release/') }}"
+    name: Detect Changes
+    uses: ./.github/workflows/detect-changed-images.yaml
+
   create-release-pr:
     name: Create or Update Release PR
     runs-on: ubuntu-latest
-    if: github.event_name == 'push' && !startsWith(github.event.ref, 'refs/heads/release/')
+    if: "github.event_name == 'push' && ${{ !contains(github.ref_name, 'release/') }}"
 
     steps:
       - name: Checkout Repository
@@ -108,19 +105,18 @@ jobs:
       - name: Update Versions in Image Descriptors
         run: |
           echo "Updating image descriptors for version ${{ env.new_version }}."
-          ./update_version.sh || { echo "Version update failed. Exiting."; exit 1; }
+          ./update_version.sh ${{ needs.changed-images.outputs.images }} || { echo "Version update failed. Exiting."; exit 1; }
 
       - name: Append Changelog
         id: generate-changelog
         run: |
-          chmod +x ./generate_changelog.sh
           ./generate_changelog.sh >> CHANGELOG.md
           echo "Generated changelog:"
           cat CHANGELOG.md
 
       - name: Commit Changes and Push Release Branch
         run: |
-          git add CHANGELOG.md image-descriptors/
+          git add .
           git commit -m "chore: prepare release ${{ env.new_version }}" || echo "No changes to commit."
           git push --force origin release/${{ env.new_version }}
 
